version: "3.8"

services:
  postgres:
    container_name: database
    image: postgres:13-alpine
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quizgame
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
  # backend:
  #   build:
  #     context: ./
  #     target: dev
  #   volumes:
  #     - .:/src
  #   command: npm run start:dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     DEBUG: nodejs-docker-express:*
